### PR TITLE
Fix missing import and export

### LINKED ISSUE #93: [rx-recompose] Observable is not defined when using rx-recompose 0.3.0-beta2

### PR DESCRIPTION
**Pull request by ahlee2326**
Resolves #93

### CODE REVIEW

**Comment by acdlite** [comment]
The idea is that rx-recompose should work with *any* Observable library, not just RxJS. So rather than import a specific library, we rely on Observable being globally polyfilled. This is the same approach most libraries use with respect to Promises.

**Comment by ahlee2326** [comment]
But none of these polyfills are current supporting Observable (http://kangax.github.io/compat-table/esnext/), so I need to hack it by adding rxjs's Observable as a global variable like what your test does?

**Comment by ahlee2326** [comment]
Nevertheless, this line is missing https://github.com/acdlite/recompose/pull/94/files#diff-a2ca7abe8afbfbe3e2af96bcad3b42d0R1

**Comment by acdlite** [comment]
> But none of these polyfills are current supporting Observable (http://kangax.github.io/compat-table/esnext/), so I need to hack it by adding rxjs's Observable as a global variable like what your test does?

Yep! I'll add docs about this before it's released.

> Nevertheless, this line is missing

Oops. Good catch.

**Pull request closed without merging**
