### PR TITLE
Update branch related docs

### PR DESCRIPTION
**Pull request by timkindberg**
- Add example for renderNothing
- improve example for renderComponent
- Clarify optional param for branch

### CODE REVIEW

**Comment by timkindberg** [comment]
Note: I put this work on a branch because I wanted to make another simultaneous pull request.

**Comment by timkindberg** [comment]
Your suggestions from previous PR have been implemented

**Comment by istarkov** [comment]
I like this, thank you. @wuct ?

**Comment by wuct** [comment]
Looks good to me. Thanks!

**Pull request merged**
