### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by maarekj**

### CODE REVIEW

**Comment by istarkov** [comment]
Thank you, IMO it's better to change on the name from real definition https://github.com/acdlite/recompose/blob/master/src/packages/recompose/withPropsOnChange.js#L7 `shouldMapOrKeys`

**Comment by wuct** [comment]
`shouldMapOrKeys` is better

**Comment by maarekj** [comment]
It is done.

**Comment by wuct** [comment]
Thanks!
The build has failed because of React unknown-props warning which is not related to this PR.

**Pull request merged**
