### PR TITLE
export createEventHandlerWithConfig for consumers

### PR DESCRIPTION
**Pull request by toddtarsi**
This is useful for environments with multiple observable types. Thanks you for the great repo!

### CODE REVIEW

**Comment by istarkov** [comment]
Tests as example see https://github.com/acdlite/recompose/search?utf8=%E2%9C%93&q=createEventHandler&type=

**Comment by toddtarsi** [comment]
Absolutely, will look at later tonight. Thanks for quick feedback. 👍

**Comment by istarkov** [comment]
Thank you!

**Comment by toddtarsi** [comment]
Actually, `NewObservable.From(stream$)` works well enough for my purposes. I turned out to not need this. Thanks for the great repo!

**Pull request closed without merging**
