### PR TITLE
Es build

### PR DESCRIPTION
**Pull request by TrySound**
not minified umd is a development version now

### CODE REVIEW

**Comment by TrySound** [comment]
There's still lotta warnings. Is it some kinda ava's cache?

**Comment by istarkov** [comment]
enzyme

**Comment by TrySound** [comment]
Oh, okay.

**Comment by TrySound** [comment]
@istarkov Do you have a plan to merge it?

**Comment by istarkov** [comment]
Need a time to review, can't answer now.

**Comment by istarkov** [comment]
See no issues with this PR, 

BTW for now we have 2 source of babel plugins (rollup config and babelrc) and this is not cool.

Having this #348 I agree that we need to prepare cjs rollup build, and then add a deprecation warning [here](https://github.com/acdlite/recompose#optimizing-bundle-size)

Is any statistics on what version of webpack is most used now exists?

**Pull request merged**
