### PR TITLE
Treeshake

### PR DESCRIPTION
**Pull request by TrySound**
Tried to treeshake whatever possible. But shallowEqual still fails because of commonjs. Bad dependency.

### CODE REVIEW

**Comment by istarkov** [comment]
I see no issues, @wuct please merge if all is ok from your side.

**Comment by istarkov** [comment]
We need to think about moving fbjs `shallowEqual` into the recompose, this will solve that `shallowEqual` is not tree shaked and included with every import.

**Comment by TrySound** [comment]
Or better, I introduce es modules in fbjs to make happy everybody.

**Comment by wuct** [comment]
Should we open a new issue for shouldComponentUpdate?

**Comment by TrySound** [comment]
In react? Or you are about shouldUpdate hoc?

**Comment by wuct** [comment]
Oh, I mean recompose/shallowEqual. I am typing on my phone. sorry for the mistake.

**Comment by wuct** [comment]
I am going to merge this PR. Let's track shallowEqual in other issue.

**Comment by TrySound** [comment]
ShallowEqual export is tree shaked. Fbjs/shallowEqual dep is not.

**Comment by TrySound** [comment]
Okay

**Comment by wuct** [comment]
@TrySound Thanks for your great work!

**Pull request merged**
