### PR TITLE
Build umd with rollup

### PR DESCRIPTION
**Pull request by TrySound**
build
- Recompose.js 76 360 -> 35 623
- Recompose.js 28 877 -> 13 028

Also I'd like to bundle es modules version soon

### CODE REVIEW

**Comment by istarkov** [comment]
Super! Will look today. Thank you

**Comment by istarkov** [comment]
Can you fix linter errors? I know we have not check them in `package.json` lint rule, but it's our mistake.

**Comment by TrySound** [comment]
Okay

**Comment by TrySound** [comment]
Do you mean release.js or that no-console wraning?

**Comment by istarkov** [comment]
All 50+ after this command ;-)

```
./node_modules/.bin/eslint ./scripts/ ./rollup.config.js
```

**Comment by istarkov** [comment]
Also I've got `Unknown plugin "babel-plugin-external-helpers" specified in "base" at 23, attempted to resolve rel
ative to "/Users/ice/ext/npm/recompose/src/packages/recompose"`

**Comment by istarkov** [comment]
Also (I'm just curious) haven't you investigated what causes so big size decrease? `webpack` module headers or some dependency?

**Comment by TrySound** [comment]
Webpack adds some boilerplate for each module. Maybe something in deps was treeshaked. Maybe Babel helpers. Or all together)

**Comment by TrySound** [comment]
@acdlite So much changed since yesterday :))

**Comment by TrySound** [comment]
Maybe fixing test fail is the purpose of different PR?

**Comment by istarkov** [comment]
Yes currently in progress https://github.com/acdlite/recompose/issues/344

**Comment by TrySound** [comment]
Wow, found 11 Object.assign and a lot more helpers. I guess this is one of main wins.

**Comment by istarkov** [comment]
I'm having strange behaviour trying to preview build results without your PR just adding `babel-plugin-external-helpers` and trying to build the project `npm run release`

```
/Users/ice/ext/npm/recompose/scripts/release.js:5
var _fs2 = babelHelpers.interopRequireDefault(_fs);
           ^

ReferenceError: babelHelpers is not defined
```

I haven't used helpers, what it can be?

**Comment by istarkov** [comment]
Have you tried resulting umd build? The same error can be there.

**Comment by TrySound** [comment]
Rollup plugin Babel adds necessary helpers. Babel loader seems not.

**Comment by TrySound** [comment]
Or its babel-node. You should have different config or add env variables. This however didn't worked in this PR. I'll try to fix it later. Maybe we even don't need babel-node, caz the last node is pretty babeled. :)

**Comment by istarkov** [comment]
Super, Thank you a lot!!!

**Pull request merged**
