### PR TITLE
Add dev dependencies required to run push scripts

### PR DESCRIPTION
**Pull request by acchou**
Added devDependencies for `change-emitter`, `hoist-non-react-statics`, and `jest-cli` that are needed to run the push scripts. This was approved in a comment in #522 .

### CODE REVIEW

**Comment by istarkov** [comment]
Why I pushed without any issues before, what changed?

**Comment by istarkov** [comment]
Did you used yarn for install?

**Comment by istarkov** [comment]
As push just run tests and deps above are already exists under recompose package. Also what the need of jest-cli as jest works well without, https://github.com/facebook/jest where here any words about jest-cli?

**Comment by acchou** [comment]
Maybe you have these deps installed globally, so don't see the issue? I was unable to push until I added these deps.

**Comment by acchou** [comment]
BTW I tried `yarn install` and I get what appears to be an infinite loop:

```

$ node scripts/installNestedPackageDeps.js
yarn install v1.0.2
yarn install v1.0.2
warning package.json: No license field
warning package.json: No license field
yarn install v1.0.2
warning No license field
[1/4] Resolving packages...
warning No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.38s.
success Already up-to-date.
Done in 0.48s.
[1/4] Resolving packages...
success Already up-to-date.
$ node scripts/installNestedPackageDeps.js
yarn install v1.0.2
warning package.json: No license field
yarn install v1.0.2
yarn install v1.0.2
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.56s.
warning No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.56s.
[1/4] Resolving packages...
success Already up-to-date.
$ node scripts/installNestedPackageDeps.js
yarn install v1.0.2
```
Which continues to call `node scripts/installNestedPackageDeps.js` repeatedly.

**Comment by istarkov** [comment]
I have no global deps. Last PR I did yesterday. I saw infinite loop in the past, break it and all will be fiine :-)

**Comment by acchou** [comment]
Not sure if it matters, but I'm on MacOS. This is what I get if I try to push without `jest-cli`:

```
$ git push

> husky - npm run -s prepush
> husky - node v7.8.0

yarn run v1.0.2
$ cross-env BABEL_ENV=rollup rollup --config scripts/rollup.config.js --environment BUILD:es,PACKAGE_NAME:recompose
✨  Done in 4.12s.
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/achou/Code/recompose/node_modules/jest-cli'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getJest (/Users/achou/Code/recompose/node_modules/jest/node_modules/jest-cli/build/cli/getJest.js:22:12)
    at Object.run (/Users/achou/Code/recompose/node_modules/jest/node_modules/jest-cli/build/cli/index.js:39:48)
    at Object.<anonymous> (/Users/achou/Code/recompose/node_modules/jest/node_modules/jest-cli/bin/jest.js:14:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

> husky - pre-push hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run prepush'
error: failed to push some refs to 'git@github.com:acchou/recompose.git'
```

**Comment by istarkov** [comment]
And Im on mac :-)

**Comment by istarkov** [comment]
I'll check now with latest yarn (I use outdated)

**Comment by istarkov** [comment]
I just checked with latest yarn and clean recompose, all is fine

image

As you could see `npm -g list | grep jest` gives nothing

**Comment by acchou** [comment]
I just tried to re-fork this and a test push worked. I don't know how I got my previous install in a bad state, but in any case I'll consider this closed.

**Pull request closed without merging**
