### PR TITLE
Add isMounted HOC

### PR DESCRIPTION
**Pull request by istarkov**
isMounted helper HOC
https://github.com/acdlite/recompose/pull/52#issuecomment-156217124

### CODE REVIEW

**Comment by acdlite** [comment]
Cool! Could we add an parameter that sets the name of the `isMounted` prop?

**Comment by istarkov** [comment]
Done. 

Looks like lodash `curry` does not allow to use default arguments,

Like

```
const isMounted = (
  isMountedPropName='isMointed',
  BaseComponent
) =>
```

Because calling curried function without arguments returns function itself `curried == curried()`
So instead of `isMounted()` user needs to write `isMounted('isMounted')`

**Comment by jimbolla** [comment]
React is planning on deprecating isMounted eventually. See https://github.com/facebook/react/issues/5465

**Comment by istarkov** [comment]
This is not react isMounted call, see the source, using asynchronous calls we need to know does component still mounted before setState call, otherwise React gives an error message. 
So if you use `raf`, `promises`, other similar calls, there is no way without such method to avoid this error message.

**Comment by istarkov** [comment]
`raf` is bad example above, we could cancel `raf` calls in `lifecycle` teardown hook,
but we can do nothing with promises.

**Comment by istarkov** [comment]
Looks like it's not a problem to write cancelable support for promise,

like this 

```
const makeCancelable = (promise) => {
  let hasCanceled_ = false;

  return {
    promise: new Promise(
      (resolve, reject) => promise
        .then(r => hasCanceled_
          ? reject({isCanceled: true})
          : resolve(r)
        )
    ),
    cancel() {
      hasCanceled_ = true;
    },
  };
};

// HOW TO USE
const somePromise = new Promise(r => setTimeout(r, 1000));

const cancelable = makeCancelable(somePromise);

cancelable
  .promise
  .then(() => console.log('resolved'))
  .catch(({isCanceled, ...error}) => console.log('isCanceled', isCanceled));

// Cancel promise
cancelable.cancel();
```

so this problem can be solved using lifecycle HOC,
so I close this PR.

**Pull request closed without merging**
