### PR TITLE
Add back lifecycle() as wrapper around React.createClass

### LINKED ISSUE #156: Request to bring back lifecycle
Hi, wanted to know the reason why you removed the `lifecycle` helper on your latest release (v0.18.0) and maybe open a vote on bringing it back in some form if anyone else uses / requires this feature.

My use case looks sth like this:

```js
const options = new Options({})

export const mapOptions = (options) => {
	return compose(
		withState('options', 'updateOptions', options.get()),
		mapProps(({updateOptions, ...rest}) => ({
			onUpdateOptions: () => {
				updateOptions(() => options.get())
			},
			...rest,
		})),
		lifecycle((component) => {
			options.on('update', component.props.onUpdateFreezer)
		}, () => {
			options.off('update', component.props.onUpdateFreezer)
		})
	)
}

const options = new Options({})
const MyOptionComponent = mapOptions(options)(MyComponent)
options.set({foo: 'bar'}) // triggers 'update'
```

Basically `options` triggers `update` event on which I would like to update the props. Maybe there's a other (better) way to do this without creating a base class and extending it!?

Cheers

### PR DESCRIPTION
**Pull request by acdlite**
Closes #156 and #68

### CODE REVIEW

**Comment by dlebedynskyi** [comment]
Note you now must use `function` instead of arrow functions 

```
lifecycle({
  	componentDidMount: function() {
     console.log('props', this.props);
    },
    componentWillReceiveProps: function (newProps) {
     console.log('new props', newProps);
     console.log('props', this.props);
    }
  }),
```
since *props are bound to context of HoC*. 
@acdlite  you might want to put it into documentation since `doOnReceiveProps`, as one of methods  it replaced,  was working differently. 
Also I update fiddle to show lifecycle https://jsfiddle.net/v6jojyej/2/

**Comment by erlis** [comment]
@acdlite, 

I was checking the jsfiddle shared by @dlebedynskyi and it really helped me in understanding what the method does. 

The documentation for recompose is really bad, most of the time when I need to understand how something works I have to open a test and read through the code because the description on the API page doesn't help much. 

I think adding some code example to the API page will help tremendously, also I like the jsfiddle idea because I can play with the example.

**Comment by acdlite** [comment]
I agree the documentation sucks. Gotta fix it soon.

**Comment by dlebedynskyi** [comment]
@acdlite as an proposal on lifecycle 
instead of method as a normal unbind function how about to use the same approach for lifecycle methods as in withHandlers 
something like this 

```
lifecycle: { 
componentWillMount: (props) => (..args) => { ... },
componentWillReceiveProps: (props) => (newProps) => {... } 
}
```
in this case we will avoid problem like above, make code styles consistent across all recompose. And overall we really just use simple  function to have access to `this.props`. What do you think?

**Comment by wuct** [comment]
I think the current implementation is fine. It is easy to understand and friendly to people who are new to `recompose`. We just need to improve the doc.

The new approach will lose the ability to access `this`, which I sometimes find useful.

**Comment by dlebedynskyi** [comment]
@wuct valid point too. we just pretty much never use this due to recompose. 
And I think in context this will be HoC lifecycle one, correct? 
how do you think that will be used?

**Comment by bholloway** [comment]
(Please excuse me in advance if I am misunderstanding the situation)

@wuct accessing `this` breaks encapsulation on the wrapped component. I think it is good if `recompose` helps you better compose your classes but I don't think this is the majority use case. Right now it feels like `lifecycle` is from a different library.

At face value I like @dlebedynskyi's proposal. I sense there is no progress because existing users will be disadvantaged, which is a fair concern.

In some ways I think it is down to a bad choice of names - `lifecycle` to me implies we are dealing with the props lifecycle (`..WillMount`, `..WillRecieveProps`, `..WillUnmount`). In comparison the current `lifecycle` implementation is just a mixin.

In hindsight it would be better called `mixin`, which serves @wuct's use case. And `lifecycle` would be free to implement something like @dlebedynskyi is suggesting.

Since this is not the case we just need to find another good name for @dlebedynskyi 's component in order to move forward.

**Comment by wuct** [comment]
@dlebedynskyi @bholloway Yes, to create/teardown info (ex: event listeners) in the lifecycle is one of the cases. Another case I encounter is to find the DOM element and get the layout info, like `offsetLeft`, `clientWidth`, etc.

**Comment by wuct** [comment]
@bholloway and yes, the current implementation of `lifecycle` is just a `mixin`. Renaming might be helpful.

**Pull request merged**
