### PR TITLE
Add withRenderProps

### PR DESCRIPTION
**Pull request by pomber**
From this [tweet](https://twitter.com/icelabaratory/status/992123859590631424). Let me know if there's anything missing.

### CODE REVIEW

**Comment by istarkov** [comment]
Super! Thank you, I will check at sunday|monday, seems like travis is broken now.

**Comment by wuct** [comment]
Is TravisCI broken now?

**Comment by istarkov** [comment]
Thanks, Ill add flowtypings and make release.

**Comment by sylvain-hamel** [comment]
What are the use cases and benefits of withRenderProps? I asked [this question on SO](https://stackoverflow.com/questions/50933396/what-are-the-use-cases-and-benefits-of-withrenderprops)  but did not get any answer. I understand the render prop pattern. What I'd like to know is when/why I would convert some of recompose's HOCs (or my own HOCs) this way, using withRenderProps.

**Pull request merged**
