### PR TITLE
added with styles

### PR DESCRIPTION
**Pull request by dankram**
This allows for easy dynamic manipulation of component styles based on props.

### CODE REVIEW

**Comment by dankram** [comment]
I still need to write tests which I would appreciate some help on.

**Comment by istarkov** [comment]
Thank you.
Having withProps what the reason of this hoc? 
Also why styles property and not theme as like in themr or any other?

**Comment by dankram** [comment]
As an example, withProps is just an extension on mapProps. I felt that people would also potentially use this a lot for dynamic styling. It may in fact be outside the scope of this project however.

**Comment by TrySound** [comment]
I think this case is quite specific.

**Comment by dankram** [comment]
That's fair. Thanks for taking a look!

**Pull request closed without merging**
