### PR TITLE
Add note about preact usage

### PR DESCRIPTION
**Pull request by ericclemmons**
In response to https://github.com/acdlite/recompose/issues/458#issuecomment-326126729.

### CODE REVIEW

**Comment by istarkov** [comment]
Thank you!!!

**Comment by istarkov** [comment]
I read somewhere that with yarn its also possible to alias some packages.

**Comment by ericclemmons** [comment]
You’re right, it’s a new(ish) feature:
> https://twitter.com/sebmck/status/873958247304232961?lang=en

**Comment by istarkov** [comment]
Thank you for a link!

**Pull request merged**
