### PR TITLE
reverse spread of props on mapPropsOnChange

### PR DESCRIPTION
**Pull request by hartzis**
fix for #102

### CODE REVIEW

**Comment by hartzis** [comment]
CI build failed due to:

Module build failed: Error: The (relay-query) Babel 5 plugin is being run with Babel 6.

I think it is related to https://github.com/facebook/relay/pull/889, and when they publish a new version it may be fixed.

**Comment by hartzis** [comment]
blocked by tests failing, #106

**Comment by hartzis** [comment]
@acdlite merged in master to get tests to run, and fixed the broken tests. Should be good to go now.

**Comment by acdlite** [comment]
Thanks!

**Comment by istarkov** [comment]
IMHO `omit` should be removed.

I'll explain why:

One of my most used construction with `mapPropsOnChange` was

```javascript
mapPropsOnChange(
  ['a', 'b', 'c'], 
  ({...props, a, b ,c}) => ({
    ...props,
    computedProps: blabla(a,b,c)
  })
),
```

spread operator allows me to not lost `a,b,c` in the future, and reuse them again.

Now to make this work I can't use spread operator at all, because other props out of selection array i.e. ['a', 'b', 'c'] will be placed in `computedProps` so will be outdated. 

The code above now looks like

```javascript
mapPropsOnChange(
  ['a', 'b', 'c'], 
  ({a, b ,c}) => ({
    a,
    b,
    c,
    computedProps: blabla(a,b,c)
  })
),
```

So every time I add property into selection array I need to add it into object to preserve. 

Removing `omit` will help a lot, I could just remove all that `...props`, and forget about property omitting logic in `mapPropsOnChange`

**Pull request merged**
