### PR TITLE
missing (BaseComponent) in compose example

### PR DESCRIPTION
**Pull request by axelmm**

### CODE REVIEW

**Comment by wuct** [comment]
The example is not wrong. `compose(hoc1, hoc2)` is a HOC; `compose(hoc1, hoc2)(BaseComponent)` is a component.

**Comment by axelmm** [comment]
Sure, I would agree **but not in context of next lines**:  "Same as ...."  - IMHO it's definitely **not the same**.

**Comment by wuct** [comment]
@axelmm 

```
const composedHoc = compose(hoc1, hoc2, hoc3)
 	 
const composedHoc = BaseComponent => hoc1(hoc2(hoc3(BaseComponent)))
```

They're same.

**Comment by axelmm** [comment]
grr, I wanted to update/continue in this thread, but created new PR #623 :(

**Pull request closed without merging**
